[2023-11-09T22:28:13.018+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.preprocess_zero_imput_norm manual__2023-11-09T22:28:05.807738+00:00 [queued]>
[2023-11-09T22:28:13.043+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: early_sepsis_prediction.preprocess_zero_imput_norm manual__2023-11-09T22:28:05.807738+00:00 [queued]>
[2023-11-09T22:28:13.044+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T22:28:13.046+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-09T22:28:13.046+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-09T22:28:13.079+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): preprocess_zero_imput_norm> on 2023-11-09 22:28:05.807738+00:00
[2023-11-09T22:28:13.090+0000] {standard_task_runner.py:55} INFO - Started process 4247 to run task
[2023-11-09T22:28:13.103+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'early_sepsis_prediction', 'preprocess_zero_imput_norm', 'manual__2023-11-09T22:28:05.807738+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpocr6hjlh']
[2023-11-09T22:28:13.108+0000] {standard_task_runner.py:83} INFO - Job 257: Subtask preprocess_zero_imput_norm
[2023-11-09T22:28:13.238+0000] {task_command.py:388} INFO - Running <TaskInstance: early_sepsis_prediction.preprocess_zero_imput_norm manual__2023-11-09T22:28:05.807738+00:00 [running]> on host 911414a99fc3
[2023-11-09T22:28:13.407+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pavs
AIRFLOW_CTX_DAG_ID=early_sepsis_prediction
AIRFLOW_CTX_TASK_ID=preprocess_zero_imput_norm
AIRFLOW_CTX_EXECUTION_DATE=2023-11-09T22:28:05.807738+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-09T22:28:05.807738+00:00
[2023-11-09T22:28:13.536+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Bilirubin_direct
- EtCO2
- Fibrinogen
- TroponinI
Feature names seen at fit time, yet now missing:
- BaseExcess
- Glucose
- HR
- Hct
- Platelets

  warnings.warn(message, FutureWarning)

[2023-11-09T22:28:13.540+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/pylab1.py", line 122, in preprocess_zero_imput_norm
    test_df.iloc[:,1:-1] = scaler.transform(test_df.iloc[:,1:-1])
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 501, in transform
    reset=False,
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 585, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 401, in _check_n_features
    f"X has {n_features} features, but {self.__class__.__name__} "
ValueError: X has 35 features, but MinMaxScaler is expecting 36 features as input.
[2023-11-09T22:28:13.578+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=early_sepsis_prediction, task_id=preprocess_zero_imput_norm, execution_date=20231109T222805, start_date=20231109T222813, end_date=20231109T222813
[2023-11-09T22:28:13.620+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 257 for task preprocess_zero_imput_norm (X has 35 features, but MinMaxScaler is expecting 36 features as input.; 4247)
[2023-11-09T22:28:13.679+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-09T22:28:13.726+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
